//This file contains data needed to be saved and pushed to localstorage (train timing details , movie show details , hotel details)
const trainTimings = [
    { departure: 'Gujranwala', destination: 'Multan', time: 18, date: '2025-06-09' },
    { departure: 'Quetta', destination: 'Karachi', time: 13, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Hyderabad', time: 10, date: '2025-06-09' },
    { departure: 'Peshawar', destination: 'Hyderabad', time: 12, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Gujranwala', time: 18, date: '2025-06-09' },
    { departure: 'Multan', destination: 'Quetta', time: 9, date: '2025-06-10' },
    { departure: 'Faisalabad', destination: 'Multan', time: 18, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Quetta', time: 12, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Quetta', time: 19, date: '2025-06-10' },
    { departure: 'Peshawar', destination: 'Hyderabad', time: 20, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Quetta', time: 17, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Karachi', time: 9, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Faisalabad', time: 15, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Multan', time: 16, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Peshawar', time: 8, date: '2025-06-11' },
    { departure: 'Karachi', destination: 'Gujranwala', time: 10, date: '2025-06-11' },
    { departure: 'Hyderabad', destination: 'Rawalpindi', time: 8, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Quetta', time: 7, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Multan', time: 9, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Peshawar', time: 16, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Gujranwala', time: 12, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Rawalpindi', time: 14, date: '2025-06-09' },
    { departure: 'Faisalabad', destination: 'Hyderabad', time: 20, date: '2025-06-11' },
    { departure: 'Faisalabad', destination: 'Karachi', time: 8, date: '2025-06-11' },
    { departure: 'Lahore', destination: 'Quetta', time: 10, date: '2025-06-10' },
    { departure: 'Karachi', destination: 'Faisalabad', time: 16, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Quetta', time: 7, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Gujranwala', time: 16, date: '2025-06-11' },
    { departure: 'Hyderabad', destination: 'Gujranwala', time: 9, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Gujranwala', time: 10, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Lahore', time: 7, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Multan', time: 11, date: '2025-06-09' },
    { departure: 'Karachi', destination: 'Peshawar', time: 7, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Karachi', time: 19, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Peshawar', time: 20, date: '2025-06-11' },
    { departure: 'Lahore', destination: 'Hyderabad', time: 6, date: '2025-06-11' },
    { departure: 'Gujranwala', destination: 'Rawalpindi', time: 7, date: '2025-06-11' },
    { departure: 'Gujranwala', destination: 'Peshawar', time: 17, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Peshawar', time: 7, date: '2025-06-11' },
    { departure: 'Hyderabad', destination: 'Lahore', time: 10, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Lahore', time: 14, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Multan', time: 19, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Multan', time: 8, date: '2025-06-11' },
    { departure: 'Karachi', destination: 'Rawalpindi', time: 14, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Multan', time: 14, date: '2025-06-09' },
    { departure: 'Quetta', destination: 'Lahore', time: 18, date: '2025-06-10' },
    { departure: 'Karachi', destination: 'Lahore', time: 8, date: '2025-06-09' },
    { departure: 'Peshawar', destination: 'Faisalabad', time: 12, date: '2025-06-10' },
    { departure: 'Peshawar', destination: 'Faisalabad', time: 7, date: '2025-06-09' },
    { departure: 'Karachi', destination: 'Quetta', time: 17, date: '2025-06-11' },
    { departure: 'Gujranwala', destination: 'Faisalabad', time: 9, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Hyderabad', time: 8, date: '2025-06-10' },
    { departure: 'Peshawar', destination: 'Quetta', time: 15, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Karachi', time: 19, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Hyderabad', time: 10, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Karachi', time: 9, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Hyderabad', time: 16, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Quetta', time: 6, date: '2025-06-11' },
    { departure: 'Gujranwala', destination: 'Karachi', time: 17, date: '2025-06-11' },
    { departure: 'Quetta', destination: 'Gujranwala', time: 6, date: '2025-06-11' },
    { departure: 'Multan', destination: 'Hyderabad', time: 7, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Rawalpindi', time: 10, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Quetta', time: 18, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Multan', time: 18, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Hyderabad', time: 17, date: '2025-06-09' },
    { departure: 'Quetta', destination: 'Faisalabad', time: 10, date: '2025-06-10' },
    { departure: 'Karachi', destination: 'Rawalpindi', time: 12, date: '2025-06-11' },
    { departure: 'Lahore', destination: 'Rawalpindi', time: 10, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Karachi', time: 19, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Karachi', time: 7, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Lahore', time: 15, date: '2025-06-09' },
    { departure: 'Peshawar', destination: 'Faisalabad', time: 17, date: '2025-06-11' },
    { departure: 'Gujranwala', destination: 'Hyderabad', time: 17, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Faisalabad', time: 9, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Lahore', time: 18, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Karachi', time: 16, date: '2025-06-11' },
    { departure: 'Faisalabad', destination: 'Multan', time: 10, date: '2025-06-11' },
    { departure: 'Quetta', destination: 'Multan', time: 13, date: '2025-06-09' },
    { departure: 'Quetta', destination: 'Karachi', time: 17, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Quetta', time: 15, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Faisalabad', time: 6, date: '2025-06-10' },
    { departure: 'Karachi', destination: 'Faisalabad', time: 20, date: '2025-06-11' },
    { departure: 'Karachi', destination: 'Quetta', time: 8, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Gujranwala', time: 19, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Hyderabad', time: 14, date: '2025-06-11' },
    { departure: 'Faisalabad', destination: 'Multan', time: 18, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Gujranwala', time: 9, date: '2025-06-09' },
    { departure: 'Quetta', destination: 'Multan', time: 7, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Multan', time: 11, date: '2025-06-11' },
    { departure: 'Faisalabad', destination: 'Gujranwala', time: 20, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Faisalabad', time: 12, date: '2025-06-11' },
    { departure: 'Quetta', destination: 'Gujranwala', time: 18, date: '2025-06-11' },
    { departure: 'Quetta', destination: 'Rawalpindi', time: 7, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Multan', time: 18, date: '2025-06-11' },
    { departure: 'Karachi', destination: 'Multan', time: 14, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Peshawar', time: 11, date: '2025-06-10' },
    { departure: 'Faisalabad', destination: 'Peshawar', time: 10, date: '2025-06-09' },
    { departure: 'Multan', destination: 'Karachi', time: 15, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Karachi', time: 6, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Hyderabad', time: 18, date: '2025-06-09' },
    { departure: 'Quetta', destination: 'Multan', time: 18, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Rawalpindi', time: 6, date: '2025-06-10' },
    { departure: 'Faisalabad', destination: 'Lahore', time: 14, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Gujranwala', time: 13, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Gujranwala', time: 10, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Quetta', time: 18, date: '2025-06-09' },
    { departure: 'Faisalabad', destination: 'Multan', time: 15, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Faisalabad', time: 6, date: '2025-06-11' },
    { departure: 'Lahore', destination: 'Quetta', time: 18, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Peshawar', time: 14, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Peshawar', time: 7, date: '2025-06-10' },
    { departure: 'Peshawar', destination: 'Gujranwala', time: 9, date: '2025-06-09' },
    { departure: 'Faisalabad', destination: 'Quetta', time: 7, date: '2025-06-10' },
    { departure: 'Karachi', destination: 'Hyderabad', time: 13, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Quetta', time: 15, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Gujranwala', time: 15, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Quetta', time: 6, date: '2025-06-09' },
    { departure: 'Faisalabad', destination: 'Peshawar', time: 20, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Karachi', time: 10, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Quetta', time: 7, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Peshawar', time: 14, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Faisalabad', time: 9, date: '2025-06-10' },
    { departure: 'Peshawar', destination: 'Rawalpindi', time: 14, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Lahore', time: 6, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Faisalabad', time: 16, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Faisalabad', time: 13, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Lahore', time: 10, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Quetta', time: 11, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Peshawar', time: 12, date: '2025-06-09' },
    { departure: 'Multan', destination: 'Gujranwala', time: 12, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Peshawar', time: 20, date: '2025-06-11' },
    { departure: 'Quetta', destination: 'Karachi', time: 12, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Multan', time: 16, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Quetta', time: 19, date: '2025-06-09' },
    { departure: 'Karachi', destination: 'Quetta', time: 12, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Quetta', time: 11, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Karachi', time: 16, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Faisalabad', time: 20, date: '2025-06-10' },
    { departure: 'Peshawar', destination: 'Quetta', time: 9, date: '2025-06-09' },
    { departure: 'Karachi', destination: 'Quetta', time: 11, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Lahore', time: 13, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Faisalabad', time: 10, date: '2025-06-11' },
    { departure: 'Quetta', destination: 'Gujranwala', time: 12, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Gujranwala', time: 13, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Karachi', time: 11, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Multan', time: 16, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Multan', time: 11, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Karachi', time: 9, date: '2025-06-11' },
    { departure: 'Karachi', destination: 'Quetta', time: 19, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Karachi', time: 9, date: '2025-06-11' },
    { departure: 'Quetta', destination: 'Multan', time: 15, date: '2025-06-10' },
    { departure: 'Gujranwala', destination: 'Quetta', time: 12, date: '2025-06-09' },
    { departure: 'Peshawar', destination: 'Gujranwala', time: 8, date: '2025-06-11' },
    { departure: 'Hyderabad', destination: 'Lahore', time: 10, date: '2025-06-11' },
    { departure: 'Multan', destination: 'Peshawar', time: 15, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Gujranwala', time: 11, date: '2025-06-11' },
    { departure: 'Faisalabad', destination: 'Peshawar', time: 9, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Multan', time: 13, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Rawalpindi', time: 6, date: '2025-06-11' },
    { departure: 'Multan', destination: 'Faisalabad', time: 19, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Gujranwala', time: 20, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Rawalpindi', time: 6, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Peshawar', time: 12, date: '2025-06-09' },
    { departure: 'Quetta', destination: 'Gujranwala', time: 20, date: '2025-06-11' },
    { departure: 'Lahore', destination: 'Karachi', time: 11, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Quetta', time: 10, date: '2025-06-11' },
    { departure: 'Hyderabad', destination: 'Karachi', time: 12, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Karachi', time: 16, date: '2025-06-10' },
    { departure: 'Quetta', destination: 'Karachi', time: 18, date: '2025-06-10' },
    { departure: 'Lahore', destination: 'Rawalpindi', time: 20, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Multan', time: 8, date: '2025-06-11' },
    { departure: 'Gujranwala', destination: 'Faisalabad', time: 16, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Quetta', time: 15, date: '2025-06-10' },
    { departure: 'Rawalpindi', destination: 'Multan', time: 13, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Gujranwala', time: 9, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Quetta', time: 19, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Faisalabad', time: 17, date: '2025-06-09' },
    { departure: 'Hyderabad', destination: 'Gujranwala', time: 18, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Faisalabad', time: 20, date: '2025-06-11' },
    { departure: 'Lahore', destination: 'Rawalpindi', time: 11, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Lahore', time: 18, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Peshawar', time: 14, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Multan', time: 13, date: '2025-06-09' },
    { departure: 'Lahore', destination: 'Faisalabad', time: 19, date: '2025-06-09' },
    { departure: 'Faisalabad', destination: 'Peshawar', time: 20, date: '2025-06-11' },
    { departure: 'Karachi', destination: 'Hyderabad', time: 10, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Karachi', time: 14, date: '2025-06-09' },
    { departure: 'Gujranwala', destination: 'Karachi', time: 14, date: '2025-06-10' },
    { departure: 'Hyderabad', destination: 'Gujranwala', time: 12, date: '2025-06-09' },
    { departure: 'Faisalabad', destination: 'Quetta', time: 6, date: '2025-06-09' },
    { departure: 'Faisalabad', destination: 'Rawalpindi', time: 10, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Faisalabad', time: 11, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Quetta', time: 8, date: '2025-06-09' },
    { departure: 'Rawalpindi', destination: 'Gujranwala', time: 8, date: '2025-06-09' },
    { departure: 'Multan', destination: 'Rawalpindi', time: 8, date: '2025-06-10' },
    { departure: 'Karachi', destination: 'Gujranwala', time: 19, date: '2025-06-09' },
    { departure: 'Peshawar', destination: 'Rawalpindi', time: 15, date: '2025-06-11' },
    { departure: 'Rawalpindi', destination: 'Hyderabad', time: 16, date: '2025-06-10' },
    { departure: 'Multan', destination: 'Quetta', time: 13, date: '2025-06-11' },
    { departure: 'Peshawar', destination: 'Karachi', time: 12, date: '2025-06-11' },
  ];

  const movieShows = [
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-10", time: "3:00 PM", movie: "Joker" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-09", time: "12:00 PM", movie: "Civil War" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-10", time: "9:00 PM", movie: "Civil War" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-09", time: "12:00 PM", movie: "Money Back Guarantee" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-11", time: "9:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-09", time: "12:00 PM", movie: "Dune: Part Two" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-09", time: "9:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-10", time: "9:00 PM", movie: "Oppenheimer" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-11", time: "11:59 PM", movie: "The Legend of Maula Jatt" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-11", time: "3:00 PM", movie: "Barbie" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-09", time: "6:00 PM", movie: "Barbie" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-10", time: "6:00 PM", movie: "Fast X" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-10", time: "9:00 PM", movie: "Oppenheimer" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-11", time: "6:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-09", time: "3:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-11", time: "12:00 PM", movie: "Joker" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-11", time: "3:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-09", time: "11:59 PM", movie: "Barbie" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-09", time: "6:00 PM", movie: "Money Back Guarantee" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-09", time: "11:59 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-10", time: "6:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "9:00 PM", movie: "Joker" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "9:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "12:00 PM", movie: "Civil War" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "9:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-09", time: "9:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-11", time: "6:00 PM", movie: "Oppenheimer" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-10", time: "11:59 PM", movie: "Barbie" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-11", time: "11:59 PM", movie: "John Wick: Chapter 4" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-09", time: "9:00 PM", movie: "Joker" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-09", time: "3:00 PM", movie: "Joker" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-10", time: "6:00 PM", movie: "Joker" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-09", time: "11:59 PM", movie: "Joker" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-10", time: "12:00 PM", movie: "Barbie" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-10", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-11", time: "12:00 PM", movie: "Oppenheimer" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-11", time: "9:00 PM", movie: "Dune: Part Two" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-09", time: "3:00 PM", movie: "Civil War" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-09", time: "6:00 PM", movie: "Dune: Part Two" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-10", time: "6:00 PM", movie: "Barbie" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-10", time: "3:00 PM", movie: "Oppenheimer" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-10", time: "6:00 PM", movie: "Joker" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-11", time: "12:00 PM", movie: "Dune: Part Two" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-09", time: "6:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-10", time: "11:59 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-11", time: "9:00 PM", movie: "Dune: Part Two" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "6:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-09", time: "11:59 PM", movie: "John Wick: Chapter 4" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-09", time: "6:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-10", time: "11:59 PM", movie: "John Wick: Chapter 4" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-10", time: "11:59 PM", movie: "Money Back Guarantee" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-10", time: "9:00 PM", movie: "Civil War" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-11", time: "11:59 PM", movie: "Joker" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-11", time: "12:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-11", time: "11:59 PM", movie: "Fast X" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-11", time: "3:00 PM", movie: "Barbie" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-10", time: "12:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-10", time: "3:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-09", time: "11:59 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-09", time: "11:59 PM", movie: "Fast X" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-10", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-10", time: "9:00 PM", movie: "Civil War" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-10", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-10", time: "9:00 PM", movie: "Dune: Part Two" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-10", time: "6:00 PM", movie: "Dune: Part Two" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-11", time: "11:59 PM", movie: "John Wick: Chapter 4" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-11", time: "6:00 PM", movie: "Dune: Part Two" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-11", time: "11:59 PM", movie: "Barbie" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-09", time: "9:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-10", time: "11:59 PM", movie: "Barbie" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-10", time: "6:00 PM", movie: "Fast X" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-10", time: "9:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-09", time: "9:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-09", time: "11:59 PM", movie: "Joker" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-11", time: "3:00 PM", movie: "Oppenheimer" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-09", time: "3:00 PM", movie: "Oppenheimer" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-10", time: "6:00 PM", movie: "Barbie" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-10", time: "11:59 PM", movie: "Joker" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-10", time: "11:59 PM", movie: "Money Back Guarantee" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-11", time: "11:59 PM", movie: "Barbie" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-10", time: "12:00 PM", movie: "Barbie" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-10", time: "6:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-09", time: "9:00 PM", movie: "Dune: Part Two" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-10", time: "3:00 PM", movie: "Civil War" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-09", time: "11:59 PM", movie: "Fast X" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-11", time: "3:00 PM", movie: "Money Back Guarantee" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-09", time: "6:00 PM", movie: "Fast X" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-10", time: "12:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-09", time: "3:00 PM", movie: "Civil War" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-09", time: "12:00 PM", movie: "Barbie" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-11", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-09", time: "12:00 PM", movie: "Money Back Guarantee" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-11", time: "6:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-10", time: "11:59 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-11", time: "6:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-10", time: "12:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-10", time: "3:00 PM", movie: "Oppenheimer" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-09", time: "3:00 PM", movie: "Fast X" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "9:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-09", time: "6:00 PM", movie: "Oppenheimer" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-10", time: "6:00 PM", movie: "Civil War" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "9:00 PM", movie: "Money Back Guarantee" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-09", time: "9:00 PM", movie: "Dune: Part Two" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-10", time: "12:00 PM", movie: "Civil War" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-10", time: "9:00 PM", movie: "Oppenheimer" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-11", time: "3:00 PM", movie: "Fast X" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-09", time: "6:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-09", time: "3:00 PM", movie: "Fast X" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-09", time: "9:00 PM", movie: "Fast X" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-10", time: "11:59 PM", movie: "Barbie" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-11", time: "11:59 PM", movie: "Money Back Guarantee" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-11", time: "6:00 PM", movie: "Civil War" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-11", time: "11:59 PM", movie: "The Legend of Maula Jatt" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-11", time: "11:59 PM", movie: "Barbie" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-11", time: "12:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-11", time: "12:00 PM", movie: "Joker" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-09", time: "9:00 PM", movie: "Money Back Guarantee" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-10", time: "11:59 PM", movie: "Oppenheimer" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-11", time: "3:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-10", time: "6:00 PM", movie: "Oppenheimer" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-11", time: "12:00 PM", movie: "Civil War" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "11:59 PM", movie: "Oppenheimer" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "6:00 PM", movie: "Money Back Guarantee" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "3:00 PM", movie: "Joker" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-10", time: "3:00 PM", movie: "Oppenheimer" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-09", time: "11:59 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-11", time: "6:00 PM", movie: "Dune: Part Two" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-09", time: "3:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-11", time: "11:59 PM", movie: "Barbie" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-10", time: "12:00 PM", movie: "Barbie" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-11", time: "6:00 PM", movie: "Barbie" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-09", time: "3:00 PM", movie: "Money Back Guarantee" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-09", time: "3:00 PM", movie: "Dune: Part Two" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-11", time: "3:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-09", time: "3:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Peshawar", cinema: "Cineplex", date: "2025-06-09", time: "12:00 PM", movie: "Money Back Guarantee" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-09", time: "9:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-11", time: "3:00 PM", movie: "Fast X" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-11", time: "6:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Peshawar", cinema: "Naz Cinema", date: "2025-06-11", time: "11:59 PM", movie: "John Wick: Chapter 4" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-11", time: "9:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-11", time: "6:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Quetta", cinema: "Millennium Mall Cinema", date: "2025-06-11", time: "6:00 PM", movie: "Money Back Guarantee" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-11", time: "9:00 PM", movie: "Joker" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-09", time: "3:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-10", time: "9:00 PM", movie: "Oppenheimer" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-09", time: "3:00 PM", movie: "Civil War" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-11", time: "9:00 PM", movie: "Fast X" },
    { city: "Quetta", cinema: "Serena Cinema", date: "2025-06-10", time: "6:00 PM", movie: "Civil War" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-09", time: "12:00 PM", movie: "Civil War" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-11", time: "3:00 PM", movie: "Oppenheimer" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-10", time: "12:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Karachi", cinema: "Nueplex", date: "2025-06-10", time: "11:59 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-11", time: "12:00 PM", movie: "Fast X" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-11", time: "12:00 PM", movie: "Joker" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-10", time: "6:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-11", time: "3:00 PM", movie: "Joker" },
    { city: "Karachi", cinema: "Atrium", date: "2025-06-10", time: "11:59 PM", movie: "Joker" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-11", time: "3:00 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-09", time: "12:00 PM", movie: "Fast X" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-11", time: "6:00 PM", movie: "Dune: Part Two" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-09", time: "3:00 PM", movie: "Civil War" },
    { city: "Lahore", cinema: "CineStar", date: "2025-06-10", time: "11:59 PM", movie: "John Wick: Chapter 4" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-09", time: "9:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-11", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-10", time: "9:00 PM", movie: "Fast X" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-10", time: "12:00 PM", movie: "Joker" },
    { city: "Lahore", cinema: "Universal Cinemas", date: "2025-06-09", time: "12:00 PM", movie: "Money Back Guarantee" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-10", time: "6:00 PM", movie: "Joker" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-09", time: "11:59 PM", movie: "Godzilla x Kong: The New Empire" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "12:00 PM", movie: "Joker" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-09", time: "9:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-11", time: "6:00 PM", movie: "Barbie" },
    { city: "Islamabad", cinema: "Centaurus Cineplex", date: "2025-06-10", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-11", time: "3:00 PM", movie: "Barbie" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-09", time: "6:00 PM", movie: "Barbie" },
    { city: "Islamabad", cinema: "The Arena", date: "2025-06-09", time: "6:00 PM", movie: "Dune: Part Two" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-10", time: "6:00 PM", movie: "Fast X" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-09", time: "12:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-10", time: "3:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-11", time: "12:00 PM", movie: "Barbie" },
    { city: "Rawalpindi", cinema: "Cinepax", date: "2025-06-11", time: "12:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-10", time: "3:00 PM", movie: "Fast X" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-09", time: "9:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-09", time: "3:00 PM", movie: "Civil War" },
    { city: "Rawalpindi", cinema: "JFC Cineplex", date: "2025-06-10", time: "6:00 PM", movie: "Fast X" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-09", time: "12:00 PM", movie: "Joker" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-10", time: "12:00 PM", movie: "Fast X" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-09", time: "3:00 PM", movie: "The Legend of Maula Jatt" },
    { city: "Faisalabad", cinema: "Cinepax", date: "2025-06-10", time: "12:00 PM", movie: "Joker" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "6:00 PM", movie: "Barbie" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-11", time: "12:00 PM", movie: "Joker" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-11", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "3:00 PM", movie: "John Wick: Chapter 4" },
    { city: "Faisalabad", cinema: "Sozo World", date: "2025-06-10", time: "11:59 PM", movie: "The Legend of Maula Jatt" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-11", time: "9:00 PM", movie: "Joker" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-10", time: "6:00 PM", movie: "Joker" },
    { city: "Multan", cinema: "Ramada Cineplex", date: "2025-06-10", time: "11:59 PM", movie: "Dune: Part Two" },
    { city: "Multan", cinema: "Universal Cinemas", date: "2025-06-11", time: "9:00 PM", movie: "Joker" },
  ];

  const hotels = [
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "5 Star", roomType: "Single", price: 6846 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "4 Star", roomType: "Double", price: 7740 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "3 Star", roomType: "Suite", price: 11903 },
    { city: "Quetta", hotelName: "Quetta Serena Hotel", hotelRating: "3 Star", roomType: "Suite", price: 11816 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "3 Star", roomType: "Single", price: 4092 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "3 Star", roomType: "Deluxe", price: 9412 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "3 Star", roomType: "Suite", price: 11825 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "3 Star", roomType: "Suite", price: 11586 },
    { city: "Peshawar", hotelName: "VIP House", hotelRating: "4 Star", roomType: "Single", price: 5359 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Single", price: 6858 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "4 Star", roomType: "Deluxe", price: 12197 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "4 Star", roomType: "Single", price: 5624 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "5 Star", roomType: "Double", price: 9794 },
    { city: "Islamabad", hotelName: "Hotel One", hotelRating: "3 Star", roomType: "Deluxe", price: 9351 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "5 Star", roomType: "Single", price: 6408 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "4 Star", roomType: "Suite", price: 15592 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "3 Star", roomType: "Single", price: 4049 },
    { city: "Quetta", hotelName: "Quetta Serena Hotel", hotelRating: "5 Star", roomType: "Double", price: 9230 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "3 Star", roomType: "Double", price: 6383 },
    { city: "Peshawar", hotelName: "VIP House", hotelRating: "5 Star", roomType: "Double", price: 9611 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "4 Star", roomType: "Deluxe", price: 12071 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "4 Star", roomType: "Single", price: 5543 },
    { city: "Peshawar", hotelName: "Pearl Continental Peshawar", hotelRating: "5 Star", roomType: "Double", price: 9853 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "5 Star", roomType: "Double", price: 10012 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Single", price: 6097 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "4 Star", roomType: "Suite", price: 16027 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "4 Star", roomType: "Deluxe", price: 11974 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "4 Star", roomType: "Suite", price: 16092 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "4 Star", roomType: "Suite", price: 15521 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "3 Star", roomType: "Deluxe", price: 8776 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "3 Star", roomType: "Deluxe", price: 9205 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "4 Star", roomType: "Double", price: 7545 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Suite", price: 18815 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "4 Star", roomType: "Single", price: 4850 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "3 Star", roomType: "Suite", price: 12405 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "3 Star", roomType: "Suite", price: 12443 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "5 Star", roomType: "Suite", price: 19381 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "4 Star", roomType: "Double", price: 7475 },
    { city: "Peshawar", hotelName: "Pearl Continental Peshawar", hotelRating: "5 Star", roomType: "Single", price: 6649 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "3 Star", roomType: "Suite", price: 12091 },
    { city: "Rawalpindi", hotelName: "Hotel Shalimar", hotelRating: "5 Star", roomType: "Deluxe", price: 14425 },
    { city: "Quetta", hotelName: "Quetta Serena Hotel", hotelRating: "4 Star", roomType: "Suite", price: 16065 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "3 Star", roomType: "Suite", price: 11516 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "5 Star", roomType: "Single", price: 6092 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "3 Star", roomType: "Double", price: 6153 },
    { city: "Islamabad", hotelName: "Hotel One", hotelRating: "4 Star", roomType: "Double", price: 7582 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "3 Star", roomType: "Suite", price: 12000 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "5 Star", roomType: "Suite", price: 19290 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "3 Star", roomType: "Suite", price: 12048 },
    { city: "Multan", hotelName: "Ramada by Wyndham", hotelRating: "5 Star", roomType: "Deluxe", price: 14245 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "3 Star", roomType: "Suite", price: 11809 },
    { city: "Multan", hotelName: "Hotel One Multan", hotelRating: "3 Star", roomType: "Double", price: 5909 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "5 Star", roomType: "Single", price: 6177 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "4 Star", roomType: "Single", price: 5555 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "3 Star", roomType: "Deluxe", price: 9116 },
    { city: "Peshawar", hotelName: "VIP House", hotelRating: "3 Star", roomType: "Suite", price: 12080 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "4 Star", roomType: "Double", price: 7735 },
    { city: "Multan", hotelName: "Ramada by Wyndham", hotelRating: "3 Star", roomType: "Single", price: 4024 },
    { city: "Multan", hotelName: "Ramada by Wyndham", hotelRating: "5 Star", roomType: "Single", price: 6093 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "3 Star", roomType: "Deluxe", price: 8995 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "3 Star", roomType: "Single", price: 3591 },
    { city: "Islamabad", hotelName: "Hotel One", hotelRating: "4 Star", roomType: "Deluxe", price: 11706 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "4 Star", roomType: "Deluxe", price: 11942 },
    { city: "Islamabad", hotelName: "Hotel One", hotelRating: "4 Star", roomType: "Deluxe", price: 11635 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "4 Star", roomType: "Single", price: 4833 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "3 Star", roomType: "Single", price: 3535 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "4 Star", roomType: "Double", price: 7769 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "4 Star", roomType: "Single", price: 5509 },
    { city: "Peshawar", hotelName: "Pearl Continental Peshawar", hotelRating: "3 Star", roomType: "Double", price: 5699 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "4 Star", roomType: "Deluxe", price: 12164 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Double", price: 9229 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Suite", price: 18933 },
    { city: "Islamabad", hotelName: "Islamabad Marriott", hotelRating: "4 Star", roomType: "Deluxe", price: 11434 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "4 Star", roomType: "Deluxe", price: 11752 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "3 Star", roomType: "Suite", price: 12070 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "3 Star", roomType: "Single", price: 4356 },
    { city: "Peshawar", hotelName: "Pearl Continental Peshawar", hotelRating: "5 Star", roomType: "Suite", price: 18866 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "3 Star", roomType: "Double", price: 6164 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "4 Star", roomType: "Single", price: 5001 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "5 Star", roomType: "Suite", price: 19211 },
    { city: "Rawalpindi", hotelName: "Hotel Shalimar", hotelRating: "5 Star", roomType: "Suite", price: 18731 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "4 Star", roomType: "Suite", price: 15906 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "5 Star", roomType: "Deluxe", price: 14031 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "5 Star", roomType: "Double", price: 9237 },
    { city: "Rawalpindi", hotelName: "Hotel Shalimar", hotelRating: "5 Star", roomType: "Single", price: 6133 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "5 Star", roomType: "Single", price: 6078 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "5 Star", roomType: "Deluxe", price: 14655 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "3 Star", roomType: "Deluxe", price: 9308 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "5 Star", roomType: "Double", price: 9637 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "3 Star", roomType: "Suite", price: 11583 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "5 Star", roomType: "Single", price: 6728 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "5 Star", roomType: "Suite", price: 19481 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "4 Star", roomType: "Deluxe", price: 11340 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "4 Star", roomType: "Double", price: 7882 },
    { city: "Islamabad", hotelName: "Islamabad Marriott", hotelRating: "4 Star", roomType: "Single", price: 4976 },
    { city: "Islamabad", hotelName: "Hotel One", hotelRating: "4 Star", roomType: "Suite", price: 15962 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "5 Star", roomType: "Deluxe", price: 14041 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "4 Star", roomType: "Suite", price: 16025 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "3 Star", roomType: "Single", price: 4105 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "3 Star", roomType: "Suite", price: 12298 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "5 Star", roomType: "Suite", price: 18831 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "4 Star", roomType: "Single", price: 4989 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "3 Star", roomType: "Single", price: 4286 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "3 Star", roomType: "Deluxe", price: 8777 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Double", price: 9370 },
    { city: "Islamabad", hotelName: "Hotel One", hotelRating: "3 Star", roomType: "Single", price: 3873 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "5 Star", roomType: "Single", price: 6498 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "4 Star", roomType: "Suite", price: 16003 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "3 Star", roomType: "Single", price: 4233 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "4 Star", roomType: "Deluxe", price: 11540 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "3 Star", roomType: "Single", price: 4315 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "4 Star", roomType: "Deluxe", price: 11230 },
    { city: "Islamabad", hotelName: "Islamabad Marriott", hotelRating: "5 Star", roomType: "Single", price: 6858 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "5 Star", roomType: "Deluxe", price: 14812 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "3 Star", roomType: "Single", price: 3805 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "3 Star", roomType: "Double", price: 6294 },
    { city: "Rawalpindi", hotelName: "Hotel Shalimar", hotelRating: "4 Star", roomType: "Deluxe", price: 11233 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "5 Star", roomType: "Double", price: 9795 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "5 Star", roomType: "Deluxe", price: 14530 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "4 Star", roomType: "Deluxe", price: 11918 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "5 Star", roomType: "Deluxe", price: 14136 },
    { city: "Peshawar", hotelName: "Pearl Continental Peshawar", hotelRating: "3 Star", roomType: "Single", price: 4474 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "4 Star", roomType: "Single", price: 5334 },
    { city: "Rawalpindi", hotelName: "Hotel Shalimar", hotelRating: "3 Star", roomType: "Double", price: 6187 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "4 Star", roomType: "Single", price: 5430 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "3 Star", roomType: "Suite", price: 12318 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "5 Star", roomType: "Single", price: 5970 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "5 Star", roomType: "Single", price: 6829 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "5 Star", roomType: "Single", price: 6762 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "5 Star", roomType: "Double", price: 9264 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "3 Star", roomType: "Double", price: 6425 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "4 Star", roomType: "Single", price: 5622 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "4 Star", roomType: "Suite", price: 15651 },
    { city: "Peshawar", hotelName: "VIP House", hotelRating: "3 Star", roomType: "Suite", price: 11871 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "4 Star", roomType: "Single", price: 5451 },
    { city: "Rawalpindi", hotelName: "Hotel Shalimar", hotelRating: "3 Star", roomType: "Deluxe", price: 9136 },
    { city: "Peshawar", hotelName: "VIP House", hotelRating: "4 Star", roomType: "Suite", price: 15649 },
    { city: "Rawalpindi", hotelName: "Pearl Continental Rawalpindi", hotelRating: "5 Star", roomType: "Single", price: 6143 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "4 Star", roomType: "Suite", price: 15512 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "4 Star", roomType: "Double", price: 7608 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "4 Star", roomType: "Single", price: 5698 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "4 Star", roomType: "Deluxe", price: 11333 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "5 Star", roomType: "Double", price: 9281 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "4 Star", roomType: "Double", price: 7512 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "5 Star", roomType: "Suite", price: 19147 },
    { city: "Multan", hotelName: "Ramada by Wyndham", hotelRating: "5 Star", roomType: "Suite", price: 19286 },
    { city: "Peshawar", hotelName: "Shelton's Rezidor", hotelRating: "4 Star", roomType: "Single", price: 5616 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "5 Star", roomType: "Double", price: 10080 },
    { city: "Peshawar", hotelName: "Pearl Continental Peshawar", hotelRating: "5 Star", roomType: "Single", price: 6196 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "4 Star", roomType: "Suite", price: 15438 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "3 Star", roomType: "Double", price: 5933 },
    { city: "Quetta", hotelName: "Quetta Serena Hotel", hotelRating: "5 Star", roomType: "Deluxe", price: 14890 },
    { city: "Islamabad", hotelName: "Islamabad Marriott", hotelRating: "4 Star", roomType: "Suite", price: 16016 },
    { city: "Quetta", hotelName: "Quetta Serena Hotel", hotelRating: "4 Star", roomType: "Double", price: 8080 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "3 Star", roomType: "Double", price: 5951 },
    { city: "Rawalpindi", hotelName: "Pearl Continental Rawalpindi", hotelRating: "5 Star", roomType: "Deluxe", price: 14699 },
    { city: "Rawalpindi", hotelName: "Pearl Continental Rawalpindi", hotelRating: "5 Star", roomType: "Single", price: 6053 },
    { city: "Multan", hotelName: "Hotel One Multan", hotelRating: "3 Star", roomType: "Double", price: 5502 },
    { city: "Karachi", hotelName: "Mövenpick Hotel", hotelRating: "4 Star", roomType: "Suite", price: 15629 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Deluxe", price: 14134 },
    { city: "Multan", hotelName: "Ramada by Wyndham", hotelRating: "3 Star", roomType: "Double", price: 6042 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "3 Star", roomType: "Deluxe", price: 9313 },
    { city: "Quetta", hotelName: "Quetta Serena Hotel", hotelRating: "3 Star", roomType: "Suite", price: 12422 },
    { city: "Rawalpindi", hotelName: "Hotel Shalimar", hotelRating: "5 Star", roomType: "Single", price: 6016 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "5 Star", roomType: "Suite", price: 19672 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "5 Star", roomType: "Suite", price: 19094 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "4 Star", roomType: "Double", price: 7447 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "4 Star", roomType: "Single", price: 5406 },
    { city: "Rawalpindi", hotelName: "Flashman's Hotel", hotelRating: "5 Star", roomType: "Double", price: 9605 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "4 Star", roomType: "Deluxe", price: 11885 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "4 Star", roomType: "Deluxe", price: 11247 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "3 Star", roomType: "Double", price: 6039 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "4 Star", roomType: "Suite", price: 15596 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "5 Star", roomType: "Single", price: 6042 },
    { city: "Peshawar", hotelName: "Pearl Continental Peshawar", hotelRating: "4 Star", roomType: "Suite", price: 15218 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "4 Star", roomType: "Single", price: 5649 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "5 Star", roomType: "Deluxe", price: 14900 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "4 Star", roomType: "Suite", price: 15400 },
    { city: "Quetta", hotelName: "Bloom Star Hotel", hotelRating: "3 Star", roomType: "Single", price: 3869 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "5 Star", roomType: "Double", price: 9435 },
    { city: "Rawalpindi", hotelName: "Pearl Continental Rawalpindi", hotelRating: "5 Star", roomType: "Deluxe", price: 14446 },
    { city: "Islamabad", hotelName: "Islamabad Marriott", hotelRating: "4 Star", roomType: "Single", price: 5123 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "3 Star", roomType: "Deluxe", price: 9348 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "4 Star", roomType: "Deluxe", price: 12000 },
    { city: "Islamabad", hotelName: "Serena Hotel", hotelRating: "4 Star", roomType: "Deluxe", price: 11235 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "5 Star", roomType: "Single", price: 6713 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "5 Star", roomType: "Deluxe", price: 14856 },
    { city: "Faisalabad", hotelName: "Silk Lounge Hotel", hotelRating: "3 Star", roomType: "Single", price: 4325 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "3 Star", roomType: "Suite", price: 11955 },
    { city: "Lahore", hotelName: "Avari Lahore", hotelRating: "4 Star", roomType: "Suite", price: 15306 },
    { city: "Lahore", hotelName: "Pearl Continental Lahore", hotelRating: "5 Star", roomType: "Suite", price: 19396 },
    { city: "Faisalabad", hotelName: "Hotel One Faisalabad", hotelRating: "4 Star", roomType: "Double", price: 8120 },
    { city: "Karachi", hotelName: "Pearl Continental Karachi", hotelRating: "4 Star", roomType: "Suite", price: 15878 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "4 Star", roomType: "Single", price: 5180 },
    { city: "Peshawar", hotelName: "VIP House", hotelRating: "4 Star", roomType: "Double", price: 7359 },
    { city: "Multan", hotelName: "Hotel Grace Inn", hotelRating: "5 Star", roomType: "Double", price: 9349 },
    { city: "Karachi", hotelName: "Avari Towers", hotelRating: "4 Star", roomType: "Double", price: 8026 },
    { city: "Quetta", hotelName: "Hotel Grand", hotelRating: "3 Star", roomType: "Deluxe", price: 8846 },
    { city: "Faisalabad", hotelName: "Grand Regent Hotel", hotelRating: "5 Star", roomType: "Single", price: 6269 },
    { city: "Lahore", hotelName: "The Nishat Hotel", hotelRating: "3 Star", roomType: "Single", price: 3947 },
  ];

// localStorage.setItem("trainTimings",JSON.stringify(trainTimings));
//Saving traintimings to localstorage

// localStorage.setItem("movieShows",JSON.stringify(movieShows));
//Saving movieShows to localstorage

// localStorage.setItem("hotels",JSON.stringify(hotels));
//Saving hotels to localstorage